on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Daisugi01/hello-world-composite-action@v4
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
